version: '3'

includes:
  db:
    taskfile: ./db/taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/taskfile.yaml
    dir: ./app

vars:
  LVL: unit # unit, it, e2e
  # process supervisor
  PSV: shell # shell, docker

tasks:
  sources:
    aliases: [src]
    desc: Check all sources
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType yes' ./...
      - cmd: go fmt ./...
      - cmd: go build ./...

  tests:
    aliases: [test]
    desc: Run specified tests
    cmds:
      - cmd: go test -tags=unit ./lib/... ./adt/... ./app/...
        if: '{{eq .LVL "unit"}}'
      - cmd: go test -run=TestIntegration ./lib/...  ./adt/... ./app/...
        if: '{{eq .LVL "it"}}'
      - cmd: go test ./stack/...
        if: '{{eq .LVL "e2e"}}'

  process:
    aliases: [proc]
    desc: Run specified process in foreground
    cmds:
      - task: app:process

  processes:
    aliases: [procs]
    desc: Start and stop all processes
    cmds:
      - task: app:process

  binaries:
    aliases: [bins]
    desc: Build all binaries if checks passed
    deps:
      - task: tests
        vars:
          LVL: unit
    cmds:
      - task: app:binary
