version: '3'

includes:
  db:
    taskfile: ./db/taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/taskfile.yaml
    dir: ./app

vars:
  # process supervisor
  PSV: shell # shell, docker

tasks:
  sources:check:
    desc: Check source changes
    cmds:
      - task: linter:vet
      - task: linter:critic
      - task: linter:revive
      - task: linter:errcheck
      - task: linter:consistent
      - task: linter:staticcheck
      - task: linter:arch

  sources:prepare:
    desc: Prepare source artifact
    cmds:
      - gofmt -s -w .
      - task: sources:generate
      - git add -A
      - task: sources:check

  sources:generate:
    desc: Generate source artifacts with goverter
    cmds:
      - go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType' ./...

  sources:verify:
    desc: Verify the current HEAD before publishing
    cmds:
      - task: tests:unit

  hooks:install:
    desc: Configure this repository to use versioned Git hooks
    cmds:
      - git config core.hooksPath .githooks

  process:
    aliases: [proc]
    desc: Run specified process in foreground
    cmds:
      - task: app:process

  container:
    aliases: [cnt]
    desc: Start specified container in background
    cmds:
      - cmd: container started

  processes:
    aliases: [procs]
    desc: Run and interrupt all processes
    cmds:
      - task: app:process

  binaries:
    aliases: [bins]
    desc: Build all binaries if checks passed
    cmds:
      - task: sources:generate
      - task: tests:unit
      - task: app:binary

  tests:*:
    desc: Run tests of specified level (unit, it, e2e).
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - cmd: go test -tags=unit ./lib/... ./adt/... ./app/... ./pool/... ./proc/...
        if: '{{eq .LEVEL "unit"}}'
      - cmd: go test -run=TestIntegration ./lib/... ./adt/... ./app/...
        if: '{{eq .LEVEL "it"}}'
      - cmd: go test -failfast ./test/...
        if: '{{eq .LEVEL "e2e"}}'

  linter:*:
    vars:
      TOOL: '{{index .MATCH 0}}'
    cmds:
      - cmd: go vet ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "vet"}}'
      - cmd: go run github.com/mgechev/revive -formatter unix -exclude ./proto/... -config ./revive.toml ./...
        if: '{{eq .TOOL "revive"}}'
      - cmd: go run github.com/go-critic/go-critic/cmd/go-critic check ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "critic"}}'
      - cmd: go run github.com/quasilyte/go-consistent ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "consistent"}}'
      - cmd: go run honnef.co/go/tools/cmd/staticcheck ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "staticcheck"}}'
      - cmd: go run github.com/kisielk/errcheck ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "errcheck"}}'
      - cmd: go run ./test/arch/cmd
        if: '{{eq .TOOL "arch"}}'

  generator:*:
    vars:
      TOOL: '{{index .MATCH 0}}'
    run: once
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType' ./...
        if: '{{eq .TOOL "goverter"}}'
