version: '3'

includes:
  db:
    taskfile: ./db/taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/taskfile.yaml
    dir: ./app
  stack:
    taskfile: ./stack/taskfile.yaml
    dir: ./stack
  image:
    taskfile: ./orch/task/image.yaml
    internal: true

tasks:
  sources:
    aliases: [src]
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType yes' ./...
      - cmd: go fmt ./...
      - cmd: go build ./...

  binaries:
    aliases: [bin]
    cmds:
      - task: app:binaries

  processes:
    aliases: [proc]
    cmds:
      - task: app:process

  packages:
    aliases: [pkg]
    cmds:
      - task: db:images
      # - task: app:image

  solution:packages:
    aliases: [sps]
    deps: [packages]
    cmds:
      - task: stack:stand
