version: '3'

includes:
  db:
    taskfile: ./db/taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/taskfile.yaml
    dir: ./app

vars:
  # process supervisor
  PSV: shell # shell, docker

tasks:
  sources:
    aliases: [src]
    preconditions:
      - sh: '[ "$(gofmt -s -l . | wc -l)" -eq 0 ]'
    deps:
      - task: linter:vet
      - task: linter:critic
      - task: linter:revive
      - task: linter:errcheck
      - task: linter:consistent
      - task: linter:staticcheck
    cmds:
      - cmd: echo success
        silent: true

  process:
    aliases: [proc]
    desc: Run specified process in foreground
    cmds:
      - task: app:process

  container:
    aliases: [cnt]
    desc: Start specified container in background
    cmds:
      - cmd: container started

  processes:
    aliases: [procs]
    desc: Run and interrupt all processes
    cmds:
      - task: app:process

  binaries:
    aliases: [bins]
    desc: Build all binaries if checks passed
    deps:
      - task: tests:unit
    cmds:
      - task: app:binary

  tests:*:
    desc: Run tests of specified level (unit, it, e2e).
    vars:
      LEVEL: '{{index .MATCH 0}}'
    deps:
      - task: generator:goverter
    cmds:
      - cmd: go test -tags=unit ./lib/... ./adt/... ./app/...
        if: '{{eq .LEVEL "unit"}}'
      - cmd: go test -run=TestIntegration ./lib/...  ./adt/... ./app/...
        if: '{{eq .LEVEL "it"}}'
      - cmd: go test -failfast ./test/...
        if: '{{eq .LEVEL "e2e"}}'

  linter:*:
    vars:
      TOOL: '{{index .MATCH 0}}'
    cmds:
      - cmd: go vet ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "vet"}}'
      - cmd: go run github.com/mgechev/revive -formatter unix  -exclude ./proto/... ./...
        if: '{{eq .TOOL "revive"}}'
      - cmd: go run github.com/go-critic/go-critic/cmd/go-critic check ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "critic"}}'
      - cmd: go run github.com/quasilyte/go-consistent ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "consistent"}}'
      - cmd: go run honnef.co/go/tools/cmd/staticcheck ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "staticcheck"}}'
      - cmd: go run github.com/kisielk/errcheck ./lib/... ./adt/... ./app/...
        if: '{{eq .TOOL "errcheck"}}'

  generator:*:
    vars:
      TOOL: '{{index .MATCH 0}}'
    run: once
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen -global 'skipCopySameType' ./...
        if: '{{eq .TOOL "goverter"}}'
