version: '3'

vars:
  CID:
    sh: >-
      find ../lib ../adt .
      -name "*.go" -exec md5sum {} + -o
      -name "Dockerfile" -exec md5sum {} +
      | LC_ALL=C sort -k 2
      | md5sum
      | head -c 7

tasks:
  binary:
    aliases: [bin]
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen ../...
      - cmd: go build -o engine main.go

  process:
    aliases: [proc]
    cmds:
      - cmd: go run github.com/jmattheis/goverter/cmd/goverter gen ../...
      - cmd: go run main.go
