version: '3'

vars:
  DB: postgres
  CID:
    sh: >-
      find {{.DB}} -type f -exec md5sum {} +
      | LC_ALL=C sort -k 2
      | md5sum
      | head -c 7

tasks:
  process:
    aliases: [proc]
    cmd: >-
      docker compose
      --file {{.DB}}/compose.yaml
      up
      --remove-orphans
      --pull missing
      --quiet-pull
      --detach
