name: Distros Workflow

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - synchronize
  merge_group:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  distros:
    uses: orglang/go-workspace/.github/workflows/distros.yaml@b2c1ce7f6b2457e6808d6e15af5e652341b99f80
    with:
      engine_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      sdk_ref: main
      workspace_ref: cf9f0abe54c4fc8b9072a7425c838612961c58a2
      run: true
