name: Distros Workflow

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - synchronize
  merge_group:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  distros:
    uses: orglang/go-workspace/.github/workflows/distros.yaml@main
    with:
      engine_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      sdk_ref: main
      workspace_ref: main
      run: ${{ github.event_name == 'merge_group' }}
