name: sources

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sources:
    uses: orglang/go-workspace/.github/workflows/engine-ci.yaml@main
    with:
      engine_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      sdk_ref: main
      workspace_ref: main
      stage: sources
