name: sources

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sources:
    uses: orglang/go-workspace/.github/workflows/engine-ci.yaml@6393b0a7f8eb258b2e7a1104e6002c766b9bafe3
    with:
      engine_ref: ${{ github.event.pull_request.head.sha }}
      sdk_ref: main
      workspace_ref: main
      stage: sources

# retrigger after allowing go-task/setup-task